// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZSY2b5bwdzNFKMec2aghDLsOtmDvLY0',
    appId: '1:38640874799:web:254146a28e6fcfe536ddda',
    messagingSenderId: '38640874799',
    projectId: 'wilayatway786',
    authDomain: 'wilayatway786.firebaseapp.com',
    databaseURL: 'https://wilayatway786-default-rtdb.firebaseio.com',
    storageBucket: 'wilayatway786.firebasestorage.app',
    measurementId: 'G-2KDLEVTG1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA33qoKYvzh3GZjg1dixlCm4JjDkOpZWMw',
    appId: '1:38640874799:android:12dbe94c648e1e7236ddda',
    messagingSenderId: '38640874799',
    projectId: 'wilayatway786',
    databaseURL: 'https://wilayatway786-default-rtdb.firebaseio.com',
    storageBucket: 'wilayatway786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfsHKbOKLLGG6ahNk7wCENSPw4gHltnD8',
    appId: '1:38640874799:ios:a06d474120c7892f36ddda',
    messagingSenderId: '38640874799',
    projectId: 'wilayatway786',
    databaseURL: 'https://wilayatway786-default-rtdb.firebaseio.com',
    storageBucket: 'wilayatway786.firebasestorage.app',
    iosBundleId: 'com.example.wilayatWayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfsHKbOKLLGG6ahNk7wCENSPw4gHltnD8',
    appId: '1:38640874799:ios:a06d474120c7892f36ddda',
    messagingSenderId: '38640874799',
    projectId: 'wilayatway786',
    databaseURL: 'https://wilayatway786-default-rtdb.firebaseio.com',
    storageBucket: 'wilayatway786.firebasestorage.app',
    iosBundleId: 'com.example.wilayatWayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHZSY2b5bwdzNFKMec2aghDLsOtmDvLY0',
    appId: '1:38640874799:web:93afb88a9b89fafc36ddda',
    messagingSenderId: '38640874799',
    projectId: 'wilayatway786',
    authDomain: 'wilayatway786.firebaseapp.com',
    databaseURL: 'https://wilayatway786-default-rtdb.firebaseio.com',
    storageBucket: 'wilayatway786.firebasestorage.app',
    measurementId: 'G-NV1JM5SXHJ',
  );
}
